// ============================================
// Supabase Type Definitions — Chainkuns
// This file is auto-generated by Supabase CLI
// ============================================

// The Database type tells TypeScript exactly what's in our Supabase database
// Every table, every column, every type — all defined here
export type Database = {
  public: {
    Tables: {
      // ── users table ──
      users: {
        Row: {
          // what a row looks like when you READ from the table
          id: string;
          wallet_address: string;
          created_at: string;
        };
        Insert: {
          // what you need to provide when INSERTING a new row
          id?: string; // optional — Supabase generates it automatically
          wallet_address: string;
          created_at?: string;
        };
        Update: {
          // what you can provide when UPDATING a row (all optional)
          id?: string;
          wallet_address?: string;
          created_at?: string;
        };
      };

      // ── organizer_profiles table ──
      organizer_profiles: {
        Row: {
          id: string;
          user_id: string;
          display_name: string;
          bio: string | null;
          logo_url: string | null;
          is_verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          display_name: string;
          bio?: string | null;
          logo_url?: string | null;
          is_verified?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          display_name?: string;
          bio?: string | null;
          logo_url?: string | null;
          is_verified?: boolean;
          created_at?: string;
        };
      };

      // ── events table ──
      events: {
        Row: {
          id: string;
          organizer_id: string;
          title: string;
          description: string | null;
          banner_image_url: string | null;
          venue: string | null;
          event_date: string;
          total_supply: number;
          ticket_price_eth: number;
          royalty_percent: number;
          contract_address: string | null;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organizer_id: string;
          title: string;
          description?: string | null;
          banner_image_url?: string | null;
          venue?: string | null;
          event_date: string;
          total_supply: number;
          ticket_price_eth: number;
          royalty_percent: number;
          contract_address?: string | null;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          organizer_id?: string;
          title?: string;
          description?: string | null;
          banner_image_url?: string | null;
          venue?: string | null;
          event_date?: string;
          total_supply?: number;
          ticket_price_eth?: number;
          royalty_percent?: number;
          contract_address?: string | null;
          status?: string;
          created_at?: string;
        };
      };

      // ── tickets table ──
      tickets: {
        Row: {
          id: string;
          event_id: string;
          token_id: number;
          owner_wallet: string;
          is_used: boolean;
          mint_tx_hash: string | null;
          idempotency_key: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          token_id: number;
          owner_wallet: string;
          is_used?: boolean;
          mint_tx_hash?: string | null;
          idempotency_key: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          token_id?: number;
          owner_wallet?: string;
          is_used?: boolean;
          mint_tx_hash?: string | null;
          idempotency_key?: string;
          created_at?: string;
        };
      };

      // ── listings table ──
      listings: {
        Row: {
          id: string;
          ticket_id: string;
          seller_wallet: string;
          price_eth: number;
          status: string;
          list_tx_hash: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          seller_wallet: string;
          price_eth: number;
          status?: string;
          list_tx_hash?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          seller_wallet?: string;
          price_eth?: number;
          status?: string;
          list_tx_hash?: string | null;
          created_at?: string;
        };
      };
    };
    Views: Record<string, never>; // no database views yet
    Functions: Record<string, never>; // no database functions yet
    Enums: Record<string, never>; // no enums yet
  };
};
