// ============================================
// Web3-Specific Types — Chainkuns
// Types for blockchain interaction, wallets,
// contracts, and SIWE authentication
// ============================================

// ── SIWE (Sign In With Ethereum) ──

// The nonce generated by the server for each sign-in attempt
export interface SiweNonce {
  nonce: string; // random string the user will sign in MetaMask
  expires_at: string; // ISO timestamp — nonce expires in 5 minutes
}

// The verified session stored after successful SIWE sign-in
export interface WalletSession {
  wallet_address: string; // verified ETH address (primary identity)
  user_id: string; // matching Supabase user UUID
  expires: string; // when the session expires
}

// ── CONTRACT INTERACTION ──

// Arguments passed to mintTicket() on the smart contract
export interface MintTicketArgs {
  to: string; // recipient wallet address
  uri: string; // IPFS metadata URI (the ticket's NFT metadata)
}

// Arguments for listTicket() — putting a ticket up for resale
export interface ListTicketArgs {
  tokenId: number; // which NFT to list
  price: bigint; // price in wei (use viem's parseEther to convert from ETH)
}

// ── ALCHEMY NFT API ──

// An NFT as returned by the Alchemy NFT API
export interface AlchemyNft {
  contract: {
    address: string; // which contract (EventTicket.sol address)
  };
  tokenId: string; // token ID as string (Alchemy always returns strings)
  tokenType: string; // "ERC721"
  name: string | null;
  description: string | null;
  image: {
    cachedUrl: string | null; // Alchemy-cached version of the IPFS image
    originalUrl: string | null; // original IPFS URL
  };
}

// The metadata stored on IPFS for each ticket NFT
export interface AlchemyNftMetadata {
  name: string; // e.g. "Ticket #42 — Summer Web3 Conference"
  description: string; // event description
  image: string; // ipfs:// URL to ticket image
  attributes: NftAttribute[]; // extra data like event date, venue, etc.
}

// A single trait in the NFT metadata
export interface NftAttribute {
  trait_type: string; // e.g. "Event Date", "Venue"
  value: string; // e.g. "March 15, 2026", "ETHDenver"
}

// ── NETWORK CONFIG ──

// Supported blockchain networks
export type SupportedChain = "sepolia" | "mainnet";

// Result of deploying a new EventTicket.sol from the frontend
export interface ContractDeployResult {
  contract_address: string; // the new contract's address on Sepolia
  deploy_tx_hash: string; // transaction that created the contract
  block_number: number; // block where it was deployed
}
